
package ssn.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.11.redhat-3
 * Sat Dec 05 16:16:00 CET 2015
 * Generated source version: 2.7.11.redhat-3
 */

@XmlRootElement(name = "createEvent", namespace = "http://ws.ssn/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createEvent", namespace = "http://ws.ssn/", propOrder = {"arg0", "arg1", "arg2", "arg3", "arg4", "arg5", "arg6", "arg7", "arg8", "arg9", "arg10"})

public class CreateEvent {

    @XmlElement(name = "arg0")
    private int arg0;
    @XmlElement(name = "arg1")
    private int arg1;
    @XmlElement(name = "arg2")
    private int arg2;
    @XmlElement(name = "arg3")
    private int arg3;
    @XmlElement(name = "arg4")
    private java.util.Date arg4;
    @XmlElement(name = "arg5")
    private java.util.Date arg5;
    @XmlElement(name = "arg6")
    private java.lang.String arg6;
    @XmlElement(name = "arg7")
    private float arg7;
    @XmlElement(name = "arg8")
    private float arg8;
    @XmlElement(name = "arg9")
    private int arg9;
    @XmlElement(name = "arg10")
    private java.util.List<java.lang.Integer> arg10;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

    public int getArg1() {
        return this.arg1;
    }

    public void setArg1(int newArg1)  {
        this.arg1 = newArg1;
    }

    public int getArg2() {
        return this.arg2;
    }

    public void setArg2(int newArg2)  {
        this.arg2 = newArg2;
    }

    public int getArg3() {
        return this.arg3;
    }

    public void setArg3(int newArg3)  {
        this.arg3 = newArg3;
    }

    public java.util.Date getArg4() {
        return this.arg4;
    }

    public void setArg4(java.util.Date newArg4)  {
        this.arg4 = newArg4;
    }

    public java.util.Date getArg5() {
        return this.arg5;
    }

    public void setArg5(java.util.Date newArg5)  {
        this.arg5 = newArg5;
    }

    public java.lang.String getArg6() {
        return this.arg6;
    }

    public void setArg6(java.lang.String newArg6)  {
        this.arg6 = newArg6;
    }

    public float getArg7() {
        return this.arg7;
    }

    public void setArg7(float newArg7)  {
        this.arg7 = newArg7;
    }

    public float getArg8() {
        return this.arg8;
    }

    public void setArg8(float newArg8)  {
        this.arg8 = newArg8;
    }

    public int getArg9() {
        return this.arg9;
    }

    public void setArg9(int newArg9)  {
        this.arg9 = newArg9;
    }

    public java.util.List<java.lang.Integer> getArg10() {
        return this.arg10;
    }

    public void setArg10(java.util.List<java.lang.Integer> newArg10)  {
        this.arg10 = newArg10;
    }

}

