
package ssn.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.11.redhat-3
 * Mon Dec 28 22:39:38 CET 2015
 * Generated source version: 2.7.11.redhat-3
 */

@XmlRootElement(name = "createEvent", namespace = "http://ws.ssn/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createEvent", namespace = "http://ws.ssn/")

public class CreateEvent {

    @XmlElement(name = "event")
    private ssn.beans.Event event;

    public ssn.beans.Event getEvent() {
        return this.event;
    }

    public void setEvent(ssn.beans.Event newEvent)  {
        this.event = newEvent;
    }

}

