
package ssn.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.11.redhat-3
 * Sun Jan 03 17:56:17 CET 2016
 * Generated source version: 2.7.11.redhat-3
 */

@XmlRootElement(name = "createReportType", namespace = "http://ws.ssn/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createReportType", namespace = "http://ws.ssn/")

public class CreateReportType {

    @XmlElement(name = "reporttype")
    private ssn.beans.ReportType reporttype;

    public ssn.beans.ReportType getReporttype() {
        return this.reporttype;
    }

    public void setReporttype(ssn.beans.ReportType newReporttype)  {
        this.reporttype = newReporttype;
    }

}

