
package ssn.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.11.redhat-3
 * Mon Dec 14 18:50:34 CET 2015
 * Generated source version: 2.7.11.redhat-3
 */

@XmlRootElement(name = "createEvent", namespace = "http://ws.ssn/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createEvent", namespace = "http://ws.ssn/")

public class CreateEvent {

    @XmlElement(name = "arg0")
    private ssn.beans.Event arg0;

    public ssn.beans.Event getArg0() {
        return this.arg0;
    }

    public void setArg0(ssn.beans.Event newArg0)  {
        this.arg0 = newArg0;
    }

}

