
package ssn.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.11.redhat-3
 * Sat Dec 19 19:00:38 CET 2015
 * Generated source version: 2.7.11.redhat-3
 */

@XmlRootElement(name = "deleteReservations", namespace = "http://ws.ssn/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deleteReservations", namespace = "http://ws.ssn/")

public class DeleteReservations {

    @XmlElement(name = "arg0")
    private java.util.List<ssn.beans.Reservation> arg0;

    public java.util.List<ssn.beans.Reservation> getArg0() {
        return this.arg0;
    }

    public void setArg0(java.util.List<ssn.beans.Reservation> newArg0)  {
        this.arg0 = newArg0;
    }

}

