
package ssn.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.11.redhat-3
 * Thu Jan 07 20:21:15 CET 2016
 * Generated source version: 2.7.11.redhat-3
 */

@XmlRootElement(name = "getEventById", namespace = "http://ws.ssn/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getEventById", namespace = "http://ws.ssn/", propOrder = {"idevent", "iduser"})

public class GetEventById {

    @XmlElement(name = "idevent")
    private int idevent;
    @XmlElement(name = "iduser")
    private int iduser;

    public int getIdevent() {
        return this.idevent;
    }

    public void setIdevent(int newIdevent)  {
        this.idevent = newIdevent;
    }

    public int getIduser() {
        return this.iduser;
    }

    public void setIduser(int newIduser)  {
        this.iduser = newIduser;
    }

}

