
package ssn.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.11.redhat-3
 * Mon Dec 28 22:39:38 CET 2015
 * Generated source version: 2.7.11.redhat-3
 */

@XmlRootElement(name = "getEventsByFilters", namespace = "http://ws.ssn/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getEventsByFilters", namespace = "http://ws.ssn/", propOrder = {"idsport", "minplayers", "maxprice", "fromdate", "todate"})

public class GetEventsByFilters {

    @XmlElement(name = "idsport")
    private int idsport;
    @XmlElement(name = "minplayers")
    private int minplayers;
    @XmlElement(name = "maxprice")
    private double maxprice;
    @XmlElement(name = "fromdate")
    private java.util.Date fromdate;
    @XmlElement(name = "todate")
    private java.util.Date todate;

    public int getIdsport() {
        return this.idsport;
    }

    public void setIdsport(int newIdsport)  {
        this.idsport = newIdsport;
    }

    public int getMinplayers() {
        return this.minplayers;
    }

    public void setMinplayers(int newMinplayers)  {
        this.minplayers = newMinplayers;
    }

    public double getMaxprice() {
        return this.maxprice;
    }

    public void setMaxprice(double newMaxprice)  {
        this.maxprice = newMaxprice;
    }

    public java.util.Date getFromdate() {
        return this.fromdate;
    }

    public void setFromdate(java.util.Date newFromdate)  {
        this.fromdate = newFromdate;
    }

    public java.util.Date getTodate() {
        return this.todate;
    }

    public void setTodate(java.util.Date newTodate)  {
        this.todate = newTodate;
    }

}

