
package ssn.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.11.redhat-3
 * Sat Jan 09 18:29:30 CET 2016
 * Generated source version: 2.7.11.redhat-3
 */

@XmlRootElement(name = "getEventsByFilters", namespace = "http://ws.ssn/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getEventsByFilters", namespace = "http://ws.ssn/", propOrder = {"iduser", "idsport", "minplayers", "maxprice", "fromdate", "todate"})

public class GetEventsByFilters {

    @XmlElement(name = "iduser")
    private int iduser;
    @XmlElement(name = "idsport")
    private int idsport;
    @XmlElement(name = "minplayers")
    private int minplayers;
    @XmlElement(name = "maxprice")
    private double maxprice;
    @XmlElement(name = "fromdate")
    private long fromdate;
    @XmlElement(name = "todate")
    private long todate;

    public int getIduser() {
        return this.iduser;
    }

    public void setIduser(int newIduser)  {
        this.iduser = newIduser;
    }

    public int getIdsport() {
        return this.idsport;
    }

    public void setIdsport(int newIdsport)  {
        this.idsport = newIdsport;
    }

    public int getMinplayers() {
        return this.minplayers;
    }

    public void setMinplayers(int newMinplayers)  {
        this.minplayers = newMinplayers;
    }

    public double getMaxprice() {
        return this.maxprice;
    }

    public void setMaxprice(double newMaxprice)  {
        this.maxprice = newMaxprice;
    }

    public long getFromdate() {
        return this.fromdate;
    }

    public void setFromdate(long newFromdate)  {
        this.fromdate = newFromdate;
    }

    public long getTodate() {
        return this.todate;
    }

    public void setTodate(long newTodate)  {
        this.todate = newTodate;
    }

}

