
package ssn.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.11.redhat-3
 * Sat Jan 09 18:29:30 CET 2016
 * Generated source version: 2.7.11.redhat-3
 */

@XmlRootElement(name = "getManagerEntitiesByIds", namespace = "http://ws.ssn/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getManagerEntitiesByIds", namespace = "http://ws.ssn/")

public class GetManagerEntitiesByIds {

    @XmlElement(name = "idmanagerentities")
    private java.util.List<java.lang.Integer> idmanagerentities;

    public java.util.List<java.lang.Integer> getIdmanagerentities() {
        return this.idmanagerentities;
    }

    public void setIdmanagerentities(java.util.List<java.lang.Integer> newIdmanagerentities)  {
        this.idmanagerentities = newIdmanagerentities;
    }

}

