
package ssn.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.11.redhat-3
 * Thu Nov 26 18:55:02 CET 2015
 * Generated source version: 2.7.11.redhat-3
 */

@XmlRootElement(name = "getSportsResponse", namespace = "http://ws.ssn/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getSportsResponse", namespace = "http://ws.ssn/")

public class GetSportsResponse {

    @XmlElement(name = "return")
    private java.util.List<ssn.beans.Sport> _return;

    public java.util.List<ssn.beans.Sport> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<ssn.beans.Sport> new_return)  {
        this._return = new_return;
    }

}

