
package ssn.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.11.redhat-3
 * Sat Dec 05 15:20:44 CET 2015
 * Generated source version: 2.7.11.redhat-3
 */

@XmlRootElement(name = "updateField", namespace = "http://ws.ssn/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateField", namespace = "http://ws.ssn/")

public class UpdateField {

    @XmlElement(name = "arg0")
    private ssn.beans.Field arg0;

    public ssn.beans.Field getArg0() {
        return this.arg0;
    }

    public void setArg0(ssn.beans.Field newArg0)  {
        this.arg0 = newArg0;
    }

}

